#!/usr/bin/env python

import os
import sys

import torch
from diffusers import StableDiffusionImg2ImgPipeline

os.makedirs("diffusers-cache", exist_ok=True)


pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2-base",
    cache_dir="diffusers-cache",
    revision="fp16",
    torch_dtype=torch.float16,
    use_auth_token=sys.argv[1],
)
